# This is a generated file. Not intended for manual editing.
services:
  evently.api:
    build:
      context: "C:\\Users\\erfan\\Documents\\_projects\\Personal\\Evently"
      dockerfile: "src/API/Evently.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57404"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "evently.api:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57404"
    volumes:
    - "C:\\Users\\erfan\\Documents\\_projects\\Personal\\Evently\\src\\API\\Evently.Api:/app:rw"
    - "C:\\Users\\erfan\\Documents\\_projects\\Personal\\Evently:/src:rw"
    - "C:\\Users\\erfan\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\erfan\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.3.0.2\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\erfan\\AppData\\Local\\Programs\\JetBrains Rider 2025.3.0.2\\bin\\\
      backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\erfan\\AppData\\Local\\JetBrains\\Rider2025.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_11_21_21_09_21:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
